# Generated by Django 2.2.6 on 2019-10-31 01:54

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published', models.BooleanField(default=False)),
                ('type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Rules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('lastModified', models.DateTimeField()),
                ('rulesContent', models.TextField()),
                ('announcementsContent', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('username', models.CharField(default='', max_length=200)),
                ('auction_number', models.IntegerField(blank=True, default=None, null=True)),
                ('email', models.EmailField(default='', max_length=200)),
                ('password', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SilentItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=200)),
                ('description', models.CharField(default='', max_length=200)),
                ('date', models.DateTimeField(default=datetime.datetime(2019, 10, 30, 19, 54, 42, 446957), verbose_name=datetime.datetime(2019, 10, 30, 19, 54, 42, 446957))),
                ('imageName', models.CharField(default='', max_length=50)),
                ('start', models.DateTimeField(blank=True, default=None, null=True)),
                ('end', models.DateTimeField(blank=True, default=None, null=True)),
                ('auction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auction_app.Auction')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LiveItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=200)),
                ('description', models.CharField(default='', max_length=200)),
                ('date', models.DateTimeField(default=datetime.datetime(2019, 10, 30, 19, 54, 42, 446957), verbose_name=datetime.datetime(2019, 10, 30, 19, 54, 42, 446957))),
                ('imageName', models.CharField(default='', max_length=50)),
                ('orderInQueue', models.IntegerField()),
                ('auction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auction_app.Auction')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auction_app.SilentItem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auction_app.User')),
            ],
        ),
    ]
