# Generated by Django 2.2.6 on 2019-11-04 22:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='liveitem',
            name='sold',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='liveitem',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 4, 15, 14, 5, 363994), verbose_name=datetime.datetime(2019, 11, 4, 15, 14, 5, 363994)),
        ),
        migrations.AlterField(
            model_name='silentitem',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 4, 15, 14, 5, 363994), verbose_name=datetime.datetime(2019, 11, 4, 15, 14, 5, 363994)),
        ),
    ]
