# Generated by Django 2.2.6 on 2019-11-02 04:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rules',
            new_name='Rule',
        ),
        migrations.AlterField(
            model_name='liveitem',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 1, 22, 23, 15, 957374), verbose_name=datetime.datetime(2019, 11, 1, 22, 23, 15, 957374)),
        ),
        migrations.AlterField(
            model_name='silentitem',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 1, 22, 23, 15, 957374), verbose_name=datetime.datetime(2019, 11, 1, 22, 23, 15, 957374)),
        ),
    ]
