# Generated by Django 2.1.5 on 2019-11-04 23:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liveitem',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 4, 16, 20, 36, 668426), verbose_name=datetime.datetime(2019, 11, 4, 16, 20, 36, 668426)),
        ),
        migrations.AlterField(
            model_name='silentitem',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 4, 16, 20, 36, 668426), verbose_name=datetime.datetime(2019, 11, 4, 16, 20, 36, 668426)),
        ),
    ]
