# Generated by Django 2.2.6 on 2019-10-30 07:07

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auction_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rules',
            name='announcementsContent',
        ),
        migrations.RemoveField(
            model_name='rules',
            name='lastModified',
        ),
        migrations.RemoveField(
            model_name='rules',
            name='rulesContent',
        ),
        migrations.AddField(
            model_name='rules',
            name='announcements_content',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='rules',
            name='last_modified',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='rules',
            name='rules_content',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='liveitem',
            name='auction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auction_app.Auction'),
        ),
        migrations.AlterField(
            model_name='liveitem',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 30, 1, 7, 19, 410033), verbose_name=datetime.datetime(2019, 10, 30, 1, 7, 19, 410033)),
        ),
        migrations.AlterField(
            model_name='silentitem',
            name='auction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auction_app.Auction'),
        ),
        migrations.AlterField(
            model_name='silentitem',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 30, 1, 7, 19, 410033), verbose_name=datetime.datetime(2019, 10, 30, 1, 7, 19, 410033)),
        ),
    ]
