# Generated by Django 2.2.6 on 2019-10-29 19:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liveitem',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 29, 19, 14, 37, 788577), verbose_name=datetime.datetime(2019, 10, 29, 19, 14, 37, 788574)),
        ),
        migrations.AlterField(
            model_name='silentitem',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 29, 19, 14, 37, 788577), verbose_name=datetime.datetime(2019, 10, 29, 19, 14, 37, 788574)),
        ),
    ]
