# Generated by Django 2.2.6 on 2019-10-31 01:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liveitem',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 30, 19, 54, 51, 559760), verbose_name=datetime.datetime(2019, 10, 30, 19, 54, 51, 559760)),
        ),
        migrations.AlterField(
            model_name='silentitem',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 30, 19, 54, 51, 559760), verbose_name=datetime.datetime(2019, 10, 30, 19, 54, 51, 559760)),
        ),
    ]
