# Generated by Django 2.2.6 on 2019-10-31 00:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liveitem',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 30, 18, 18, 30, 461232), verbose_name=datetime.datetime(2019, 10, 30, 18, 18, 30, 461232)),
        ),
        migrations.AlterField(
            model_name='silentitem',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 30, 18, 18, 30, 461232), verbose_name=datetime.datetime(2019, 10, 30, 18, 18, 30, 461232)),
        ),
    ]
