# Generated by Django 2.2.5 on 2019-10-21 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rules',
            old_name='lastRevised',
            new_name='lastModified',
        ),
    ]
