# Generated by Django 2.2.6 on 2019-11-02 21:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction_app', '0002_auto_20191102_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liveitem',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 2, 15, 10, 20, 992032), verbose_name=datetime.datetime(2019, 11, 2, 15, 10, 20, 992032)),
        ),
        migrations.AlterField(
            model_name='silentitem',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 2, 15, 10, 20, 992032), verbose_name=datetime.datetime(2019, 11, 2, 15, 10, 20, 992032)),
        ),
    ]
