# Generated by Django 2.2.6 on 2019-11-04 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction_app', '0002_auto_20191104_1514'),
        ('auction_app', '0002_auto_20191102_2027'),
    ]

    operations = [
    ]
