# Generated by Django 2.2.6 on 2019-10-29 19:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction_app', '0002_auto_20191029_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liveitem',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 29, 19, 53, 39, 627483), verbose_name=datetime.datetime(2019, 10, 29, 19, 53, 39, 627479)),
        ),
        migrations.AlterField(
            model_name='silentitem',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 29, 19, 53, 39, 627483), verbose_name=datetime.datetime(2019, 10, 29, 19, 53, 39, 627479)),
        ),
    ]
