# Generated by Django 2.2.6 on 2019-11-05 19:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction_app', '0003_merge_20191105_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='type',
            field=models.CharField(choices=[('silent', 'Silent'), ('live', 'Live')], max_length=10),
        ),
        migrations.AlterField(
            model_name='liveitem',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 5, 12, 13, 12, 4863), verbose_name=datetime.datetime(2019, 11, 5, 12, 13, 12, 4863)),
        ),
        migrations.AlterField(
            model_name='silentitem',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 5, 12, 13, 12, 4863), verbose_name=datetime.datetime(2019, 11, 5, 12, 13, 12, 4863)),
        ),
    ]
