# Generated by Django 2.2.6 on 2019-11-06 01:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction_app', '0003_merge_20191104_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionuser',
            name='has_paid',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='bid',
            name='isWinning',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='liveitem',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 5, 18, 45, 19, 869409), verbose_name=datetime.datetime(2019, 11, 5, 18, 45, 19, 869409)),
        ),
        migrations.AlterField(
            model_name='silentitem',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 5, 18, 45, 19, 869409), verbose_name=datetime.datetime(2019, 11, 5, 18, 45, 19, 869409)),
        ),
    ]
