# Generated by Django 2.2.6 on 2019-11-04 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction_app', '0002_auto_20191101_2223'),
        ('auction_app', '0004_auto_20191102_1510'),
    ]

    operations = [
    ]
