# Generated by Django 2.2.6 on 2019-11-06 01:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction_app', '0004_auto_20191105_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionuser',
            name='amount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='liveitem',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 5, 18, 56, 48, 846395), verbose_name=datetime.datetime(2019, 11, 5, 18, 56, 48, 846395)),
        ),
        migrations.AlterField(
            model_name='silentitem',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 5, 18, 56, 48, 846395), verbose_name=datetime.datetime(2019, 11, 5, 18, 56, 48, 846395)),
        ),
    ]
